baseURL = "/"
languageCode = "ko-kr"
title = "My Life Story"
theme = "PaperMod"
paginate = 10

enableRobotsTXT = true

[params]
  env = "production"
  defaultTheme = "light"
  subtitle = "Not bound by routine, I create my own destiny."
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  disableSpecial1stPost = true
  hidemeta = false
  comments = false
  mainSections = ["philosophy", "finance", "life-wisdom"]

  [params.assets]
    theme_color = "#1e1e1e"

[menu]
  [[menu.main]]
    identifier = "philosophy"
    name = "철학"
    url = "/philosophy/"
    weight = 10
  [[menu.main]]
    identifier = "finance"
    name = "재테크"
    url = "/finance/"
    weight = 20
  [[menu.main]]
    identifier = "life-wisdom"
    name = "처세"
    url = "/life-wisdom/"
    weight = 30
